### PR TITLE
devilutionX: update to 1.4.1.

### PR DESCRIPTION
**Pull request by kruceter**
#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by bugcrazy** [comment]
ZeroTierOne is limited to a few cpus architectures and in addition it does not support the musl library, you need to have a ZeroTierOne account to use the service: https://github.com/zerotier/libzt/issues/197

Looking at your template, it's very interesting to see, new ways of thinking and solving problems :)

**Comment by kruceter** [comment]
> ZeroTierOne is limited to a few cpus architectures

How come? It compiles for all architectures in CI, even aarch64.

> does not support the musl library

If it was not supporting musl, the compilation could fail, right?

> ZeroTierOne account to use the service

Unfortunately, I am not aware myself of what exactly this feature does besides acting as another "hamachi" of sorts.

However, if you find this functionality harmful - you can disable it.


Thank you for the feedback.

As you can see, there is no need to put another cmake file for SDL2 or add new packages when something similar can be used.

**Comment by bugcrazy** [comment]
Really don't need cmake file to find SDL2!

In practice ZeroTierOne, it is useless to use in devilutionX, because an account is required to use it.

Does not compile for PPC architecture and ARM, MIPS variants.

There is no ZeroTierOne version for Alpine Linux.

**Comment by kruceter** [comment]
> In practice ZeroTierOne, it is useless to use in devilutionX, because an account is required to use it.

Just discussed this with other core member on IRC. Came to the conclusion to cut this feature out. I am still building it locally, so it will be pushed here within 15 minutes.

**Comment by kruceter** [comment]
Moved to upstream.

**Pull request closed without merging**
